### ISSUE TITLE
Json file storage

### ISSUE THREAD

**Issue by repollo** [sergeybok/BaseBot#8]
Hi

Cool project!

Is there a way to save the json conversations to a specific directory?

```python
class JsonUtil(DbUtil):
    def save_messages(self):
        with open(self.json_name, 'w') as f:
            json.dump(self.messages, f)
```

I see the above method but I think it doesn't have a way to specify a custom directory, am I correct in my assumption or is there another way to handle saving the json file? If not it would be a good addition, since right now in the project im working on, is saving the file to its root directory which is not a desirable behavior. I mean, I want to keep the json conversations in a separate directory in a specific directory, i.e.

Any of the two first behaviors could be a good implementation,

Either a custom directory for the conversations inside my project_directory
```
project_directory/
    project_module1/
    project_module2/
    project_module3/
    basebot/
        main.py # my basebot custom llm model implementation
        readme.md
    conversations/
        bot1.json
        bot2.json
        bot3.json
```
Or a custom directory for the conversations inside the basebot implementation directory,
```
project_directory/
    project_module1/
    project_module2/
    project_module3/
    basebot/
        main.py # my basebot custom llm model implementation
        readme.md
        conversations/
            bot1.json
            bot2.json
            bot3.json
```

However right now the current implementation is doing this,

```
project_directory/
    project_module1/
    project_module2/
    project_module3/
    basebot/
        main.py # my basebot custom llm model implementation
        readme.md
    bot1.json
    bot2.json
    bot3.json
```

Either way this is a cool project and would like to see it grow! Btw I found it in reddit!

EDIT 1:
After looking at the code a little bit I think that a fast and hacky way of doing it without to much trouble is by adding a handful of small lines of code to the following files,

`basebot_models.py`:
```python
class BaseBotWithLocalDb(BaseBot):
    # def __init__(self, db_util: DbUtil = None, **kwargs):
    def __init__(self, db_util: DbUtil = None, directory=None, **kwargs):
        super().__init__(**kwargs)
        if db_util:
            self.db_util = db_util
        else:
            if 'MONGO_URI' in os.environ:
                self.db_util = MongoUtil()
                try:
                    self.db_util.create_index_if_not_exists(self.bot_id, 'sender_id')
                    self.db_util.create_index_if_not_exists(self.bot_id, 'recipient_id')
                except Exception as e:
                    print('Failed to create indexes with exception: ', e)
                
            else:
                # self.db_util = JsonUtil(bot_id=self.bot_id)
                self.db_util = JsonUtil(bot_id=self.bot_id, directory=directory)

```

`database_util.py`:
```python
class JsonUtil(DbUtil):
    # def __init__(self, bot_id=str):
    def __init__(self, bot_id=str, directory=None):
        super().__init__()
        self.messages: Dict[List[Dict]] = {}
        self.bot_id = bot_id
        self.json_name = bot_id + '_messages.json'
        ### ADD FROM HERE ###
        if directory:
            os.makedirs(directory, exist_ok=True)
            self.json_name = os.path.join(directory, self.json_name)
        ### ADD TO HERE ###
        self.load_messages()
```

With this one can then do the following when creating a bot,

Instead of this:
```python
# initialize the bot, or bots
bot = ChatGPTBot()
```

We can do this:
```python
# initialize the bot, or bots
custom_directory = "/path/to/custom/directory"
bot = ChatGPTBot(directory=custom_directory)
```

**Comment by sergeybok** [comment]
Your hacky solution makes sense. I also could just add a default "conversations/" directory that it saves to by default (since right now it's just in the main folder which you're right if you have a bunch of bots will lead to things being disorganized) and then your code of providing specific directory can be optional. 

I'll try to get that out today or tomorrow. 

Also I added the JSON option sort of as a hack at the very end in order to get people to be able to launch a bot immediately. But I really recommend setting up a local mongodb server for this because it's just much more organized, and scales much better than a json file.

**Comment by repollo** [comment]
I actually like json, since openai now gives you the option to download your conversation history as json, which might be cool to add to this kind of projects in the future. Anyways thanks for the time, and keep it up!

**Comment by sergeybok** [comment]
Just merged the code. 

```
class BaseBotWithLocalDb(BaseBot):
    def __init__(self, db_util: DbUtil = None, json_directory='conversations', **kwargs):
```

Now BaseBotWithLocalDb takes as argument `json_directory` and automatically creates the directory if it doesn't exist. 

PS you probably need to uninstall and reinstall the library to get this. I'm gonna figure out how to do a proper pip package soon so it's just a pip --upgrade call, but haven't gotten around to it. 

Thanks for the suggestion!

**Comment by repollo** [comment]
> Just merged the code.
> 
> ```
> class BaseBotWithLocalDb(BaseBot):
>     def __init__(self, db_util: DbUtil = None, json_directory='conversations', **kwargs):
> ```
> 
> Now BaseBotWithLocalDb takes as argument `json_directory` and automatically creates the directory if it doesn't exist.
> 
> PS you probably need to uninstall and reinstall the library to get this. I'm gonna figure out how to do a proper pip package soon so it's just a pip --upgrade call, but haven't gotten around to it.
> 
> Thanks for the suggestion!

Just tried it, this is awesome, now I can hide the conversations inside the project's directory without having to expose the json files all over the place! Thanks your awesome!
